Additional schemas for local debugging
adobe/commerce-events pull request #167
Opened 2024-09-03 19:27 UTC by shiftedreality

## Description

This PR adds additional schemas for local debugging.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

2024-09-03 19:48 UTC, benjaminkalk requested changes
Also, also missing schemas for search-result-category, search-result-suggestion

2024-09-03 19:48 UTC, benjaminkalk commented on examples/events/snowplow-debugger/data-services-extension.json
This does not align with what exists in snowplow console

2024-09-06 20:13 UTC, shiftedreality commented on examples/events/snowplow-debugger/data-services-extension.json
Updated

2024-10-14 21:30 UTC, benjaminkalk approved these changes

2024-10-17 14:11 UTC, merged